version: '3'

services:
  postgresql:
    image: postgres:latest
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: asdf1234
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  pgadim:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadim4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: asdf1234
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin